development:
  adapter: postgresql
  encoding: unicode
  database: news_feed_development
  pool: 5
  username: quosap
  password: graceling
  host: /tmp

production:
  adapter: postgresql
  encoding: unicode
  database: news_feed_production
  pool: 5
  username: quosap
  password: graceling
  host: /tmp

test: &test
  adapter: postgresql
  encoding: unicode
  database: news_feed_test
  pool: 5
  username: quosap
  password: graceling
  host: /tmp

cucumber:
  <<: *test